<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiplomaTest1.BLL\DiplomaTest1.BLL.csproj" />
    <ProjectReference Include="..\DiplomaTest1.Core\DiplomaTest1.Core.csproj" />
  </ItemGroup>

</Project>
